import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'te', 'kn', 'hi', 'ta', 'ml'];

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? teText = '',
    String? knText = '',
    String? hiText = '',
    String? taText = '',
    String? mlText = '',
  }) =>
      [enText, teText, knText, hiText, taText, mlText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.toString());

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    '1897s6rl': {
      'en': 'Vegetables',
      'hi': 'सब्ज़ियाँ',
      'kn': 'ತರಕಾರಿಗಳು',
      'ml': 'പച്ചക്കറികൾ',
      'ta': 'காய்கறிகள்',
      'te': 'కూరగాయలు',
    },
    'fjiezwmo': {
      'en': 'ADD',
      'hi': 'जोड़ें',
      'kn': 'ಸೇರಿಸಿ',
      'ml': 'ചേർക്കുക',
      'ta': 'கூட்டு',
      'te': 'జోడించు',
    },
    '26amwcgc': {
      'en': 'Fruits',
      'hi': 'फल',
      'kn': 'ಹಣ್ಣುಗಳು',
      'ml': 'പഴങ്ങൾ',
      'ta': 'பழங்கள்',
      'te': 'పండ్లు',
    },
    'cjojnl2b': {
      'en': 'Home',
      'hi': 'घर',
      'kn': 'ಮನೆ',
      'ml': 'വീട്',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // ProfilePage
  {
    'dy7idtme': {
      'en': 'Active',
      'hi': 'सक्रिय',
      'kn': 'ಸಕ್ರಿಯ',
      'ml': 'സജീവമാണ്',
      'ta': 'செயலில்',
      'te': 'చురుకుగా',
    },
    '56pola93': {
      'en': 'Switch to Dark Mode',
      'hi': 'डार्क मोड में स्विच करें',
      'kn': 'ಡಾರ್ಕ್ ಮೋಡ್‌ಗೆ ಬದಲಿಸಿ',
      'ml': 'ഡാർക്ക് മോഡിലേക്ക് മാറുക',
      'ta': 'டார்க் பயன்முறைக்கு மாறவும்',
      'te': 'డార్క్ మోడ్‌కి మారండి',
    },
    'qvp1b553': {
      'en': 'Switch to Light Mode',
      'hi': 'लाइट मोड में स्विच करें',
      'kn': 'ಲೈಟ್ ಮೋಡ್‌ಗೆ ಬದಲಿಸಿ',
      'ml': 'ലൈറ്റ് മോഡിലേക്ക് മാറുക',
      'ta': 'லைட் பயன்முறைக்கு மாறவும்',
      'te': 'లైట్ మోడ్‌కి మారండి',
    },
    'hfki9h1q': {
      'en': 'Edit Profile',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'kn': 'ಪ್ರೊಫೈಲ್ ಬದಲಿಸು',
      'ml': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'ta': 'சுயவிவரத்தைத் திருத்து',
      'te': 'ప్రొఫైల్‌ని సవరించండి',
    },
    '45cq6ely': {
      'en': 'Change Language',
      'hi': 'भाषा बदलो',
      'kn': 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
      'ml': 'ഭാഷ മാറ്റുക',
      'ta': 'மொழியை மாற்றவும்',
      'te': 'భాష మార్చు',
    },
    '5dl9craj': {
      'en': 'Log Out',
      'hi': 'लॉग आउट',
      'kn': 'ಲಾಗ್ ಔಟ್',
      'ml': 'ലോഗ് ഔട്ട് ചെയ്യുക',
      'ta': 'வெளியேறு',
      'te': 'లాగ్ అవుట్ చేయండి',
    },
    'l07jbtaw': {
      'en': '__',
      'hi': '__',
      'kn': '__',
      'ml': '__',
      'ta': '__',
      'te': '__',
    },
  },
  // ChooseYourLanguage
  {
    'an313g8m': {
      'en': 'Choose Your Language',
      'hi': 'अपनी भाषा चुनिए',
      'kn': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'ml': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'ta': 'உங்கள் மொழியை தேர்வு செய்யவும்',
      'te': 'మీ భాషను ఎంచుకోండి',
    },
    'rwhzcgq0': {
      'en': 'English',
      'hi': 'English',
      'kn': 'English',
      'ml': 'English',
      'ta': 'English',
      'te': 'English',
    },
    'u8kfq2ut': {
      'en': 'తెలుగు',
      'hi': 'తెలుగు',
      'kn': 'తెలుగు',
      'ml': 'తెలుగు',
      'ta': 'తెలుగు',
      'te': 'తెలుగు',
    },
    'w59ly3ty': {
      'en': 'Telugu',
      'hi': 'Telugu',
      'kn': 'Telugu',
      'ml': 'Telugu',
      'ta': 'Telugu',
      'te': 'Telugu',
    },
    'xg0g4sr3': {
      'en': 'ಕನ್ನಡ',
      'hi': 'ಕನ್ನಡ',
      'kn': 'ಕನ್ನಡ',
      'ml': 'ಕನ್ನಡ',
      'ta': 'ಕನ್ನಡ',
      'te': 'ಕನ್ನಡ',
    },
    'xh7q6jt3': {
      'en': 'Kannada',
      'hi': 'Kannada',
      'kn': 'Kannada',
      'ml': 'Kannada',
      'ta': 'Kannada',
      'te': 'Kannada',
    },
    'p02n23u6': {
      'en': 'தமிழ்',
      'hi': 'தமிழ்',
      'kn': 'தமிழ்',
      'ml': 'தமிழ்',
      'ta': 'தமிழ்',
      'te': 'தமிழ்',
    },
    '86pkktnk': {
      'en': 'Tamil',
      'hi': 'Tamil',
      'kn': 'Tamil',
      'ml': 'Tamil',
      'ta': 'Tamil',
      'te': 'Tamil',
    },
    'ufkzikph': {
      'en': 'हिन्दी',
      'hi': 'हिन्दी',
      'kn': 'हिन्दी',
      'ml': 'हिन्दी',
      'ta': 'हिन्दी',
      'te': 'हिन्दी',
    },
    '0fm0zaus': {
      'en': 'Hindi',
      'hi': 'Hindi',
      'kn': 'Hindi',
      'ml': 'Hindi',
      'ta': 'Hindi',
      'te': 'Hindi',
    },
    '8p4wtyfr': {
      'en': 'മലയാളം',
      'hi': 'മലയാളം',
      'kn': 'മലയാളം',
      'ml': 'മലയാളം',
      'ta': 'മലയാളം',
      'te': 'മലയാളം',
    },
    'er6qex90': {
      'en': 'Malayalam',
      'hi': 'Malayalam',
      'kn': 'Malayalam',
      'ml': 'Malayalam',
      'ta': 'Malayalam',
      'te': 'Malayalam',
    },
    'vza4dv5j': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // Cart
  {
    'mwia8r7s': {
      'en': 'Your Cart items',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'sj2u13ab': {
      'en': 'Total in Rs:',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'zlpe1qm4': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '30tlit86': {
      'en': 'Controller Basic',
      'hi': 'नियंत्रक मूल',
      'kn': 'ನಿಯಂತ್ರಕ ಮೂಲ',
      'ml': 'കൺട്രോളർ അടിസ്ഥാനം',
      'ta': 'கட்டுப்படுத்தி அடிப்படை',
      'te': 'కంట్రోలర్ బేసిక్',
    },
    'f2bcy0o8': {
      'en': '\$125.50',
      'hi': '\$125.50',
      'kn': '\$125.50',
      'ml': '\$125.50',
      'ta': '\$125.50',
      'te': '\$125.50',
    },
    '7l19qizu': {
      'en': 'Quanity: 1',
      'hi': 'मात्रा: 1',
      'kn': 'ಪ್ರಮಾಣ: 1',
      'ml': 'അളവ്: 1',
      'ta': 'அளவு: 1',
      'te': 'పరిమాణం: 1',
    },
    'wbq47mno': {
      'en': 'Price Breakdown',
      'hi': 'मूल्य विभाजन',
      'kn': 'ಬೆಲೆ ವಿಭಜನೆ',
      'ml': 'വില ബ്രേക്ക്ഡൗൺ',
      'ta': 'விலை முறிவு',
      'te': 'ధర విభజన',
    },
    'squ6wh06': {
      'en': 'Total Price',
      'hi': 'आधार मूल्य',
      'kn': 'ಮೂಲ ಬೆಲೆ',
      'ml': 'അടിസ്ഥാന വില',
      'ta': 'அடிப்படை விலை',
      'te': 'బేస్ ధర',
    },
    'hlm4apus': {
      'en': '120',
      'hi': '\$156.00',
      'kn': '\$156.00',
      'ml': '\$156.00',
      'ta': '\$156.00',
      'te': '\$156.00',
    },
    'ukh3c0qx': {
      'en': 'Taxes',
      'hi': 'करों',
      'kn': 'ತೆರಿಗೆಗಳು',
      'ml': 'നികുതികൾ',
      'ta': 'வரிகள்',
      'te': 'పన్నులు',
    },
    '4v3bjjc7': {
      'en': '\$24.20',
      'hi': '\$24.20',
      'kn': '\$24.20',
      'ml': '\$24.20',
      'ta': '\$24.20',
      'te': '\$24.20',
    },
    'n4xla69y': {
      'en': 'Cleaning Fee',
      'hi': 'साफ करने की फीस',
      'kn': 'ಶುಚಿಗೊಳಿಸುವ ಶುಲ್ಕ',
      'ml': 'ക്ലീനിംഗ് ഫീസ്',
      'ta': 'சுத்தம் கட்டணம்',
      'te': 'శుభ్రపరిచే రుసుము',
    },
    'x909f2d5': {
      'en': '\$40.00',
      'hi': '\$40.00',
      'kn': '\$40.00',
      'ml': '\$40.00',
      'ta': '\$40.00',
      'te': '\$40.00',
    },
    'dzx3z9no': {
      'en': 'Total',
      'hi': 'कुल',
      'kn': 'ಒಟ್ಟು',
      'ml': 'ആകെ',
      'ta': 'மொத்தம்',
      'te': 'మొత్తం',
    },
    'v47cyy61': {
      'en': '',
      'hi': '\$230.20',
      'kn': '\$230.20',
      'ml': '\$230.20',
      'ta': '\$230.20',
      'te': '\$230.20',
    },
    'kij1nqms': {
      'en': 'Confirm Order',
      'hi': 'चेकआउट (\$230.20)',
      'kn': 'ಚೆಕ್ಔಟ್ (\$230.20)',
      'ml': 'ചെക്ക്ഔട്ട് (\$230.20)',
      'ta': 'செக்அவுட் (\$230.20)',
      'te': 'చెక్అవుట్ (\$230.20)',
    },
    '06rm6rgn': {
      'en': 'Rs 250',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'pb6cvypk': {
      'en': 'Home',
      'hi': 'घर',
      'kn': 'ಮನೆ',
      'ml': 'വീട്',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // Categories
  {
    'aae6o3df': {
      'en': 'Page Title',
      'hi': 'पृष्ठ का शीर्षक',
      'kn': 'ಪುಟದ ಶೀರ್ಷಿಕೆ',
      'ml': 'പേജിന്റെ പേര്',
      'ta': 'பக்கத்தின் தலைப்பு',
      'te': 'పుట శీర్షిక',
    },
    '0hokydvc': {
      'en': 'Home',
      'hi': 'घर',
      'kn': 'ಮನೆ',
      'ml': 'വീട്',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // LoginPage
  {
    'mle6qn6w': {
      'en': 'Login',
      'hi': 'लॉग इन करें',
      'kn': 'ಲಾಗಿನ್ ಮಾಡಿ',
      'ml': 'ലോഗിൻ',
      'ta': 'உள்நுழைய',
      'te': 'ప్రవేశించండి',
    },
    'gnork0pb': {
      'en': 'Email Address',
      'hi': 'ईमेल पता',
      'kn': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'ml': 'ഈ - മെയില് വിലാസം',
      'ta': 'மின்னஞ்சல் முகவரி',
      'te': 'ఇమెయిల్ చిరునామా',
    },
    'uz9yt7zl': {
      'en': 'Enter your email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'kn': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ...',
      'ml': 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക...',
      'ta': 'மின்னஞ்சலை பதிவுசெய்...',
      'te': 'మీ ఇమెయిల్‌ని నమోదు చేయండి...',
    },
    'rjevbbrv': {
      'en': 'Password',
      'hi': 'पासवर्ड',
      'kn': 'ಗುಪ್ತಪದ',
      'ml': 'Password',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
    },
    '5s0k27up': {
      'en': 'Enter your password...',
      'hi': 'अपना पासवर्ड डालें...',
      'kn': 'ನಿಮ್ಮ ಗುಪ್ತಪದವನ್ನು ನಮೂದಿಸಿ...',
      'ml': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക...',
      'ta': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்...',
      'te': 'మీ పాస్వర్డ్ ని నమోదుచేయండి...',
    },
    'fru7r08n': {
      'en': 'Login',
      'hi': 'लॉग इन करें',
      'kn': 'ಲಾಗಿನ್ ಮಾಡಿ',
      'ml': 'ലോഗിൻ',
      'ta': 'உள்நுழைய',
      'te': 'ప్రవేశించండి',
    },
    'd5ypomji': {
      'en': 'Forgot Password',
      'hi': 'पासवर्ड भूल गए',
      'kn': 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ',
      'ml': 'പാസ്വേഡ് മറന്നോ',
      'ta': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
      'te': 'పాస్‌వర్డ్ మర్చిపోయాను',
    },
    '68gpjr47': {
      'en': 'Continue as Guest',
      'hi': 'अतिथि के रूप में जारी रखें',
      'kn': 'ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ',
      'ml': 'അതിഥിയായി തുടരുക',
      'ta': 'விருந்தினராக தொடரவும்',
      'te': 'అతిథిగా కొనసాగండి',
    },
    'f9bstli9': {
      'en': 'Register',
      'hi': 'पंजीकरण करवाना',
      'kn': 'ನೋಂದಣಿ',
      'ml': 'രജിസ്റ്റർ ചെയ്യുക',
      'ta': 'பதிவு',
      'te': 'నమోదు చేసుకోండి',
    },
    '4j62cmhn': {
      'en': 'Email Address',
      'hi': 'ईमेल पता',
      'kn': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'ml': 'ഈ - മെയില് വിലാസം',
      'ta': 'மின்னஞ்சல் முகவரி',
      'te': 'ఇమెయిల్ చిరునామా',
    },
    'd8v7net5': {
      'en': 'Enter your email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'kn': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ...',
      'ml': 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക...',
      'ta': 'மின்னஞ்சலை பதிவுசெய்...',
      'te': 'మీ ఇమెయిల్‌ని నమోదు చేయండి...',
    },
    '25majzvi': {
      'en': 'Password',
      'hi': 'पासवर्ड',
      'kn': 'ಗುಪ್ತಪದ',
      'ml': 'Password',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
    },
    '7zhzb8h2': {
      'en': 'Enter your password...',
      'hi': 'अपना पासवर्ड डालें...',
      'kn': 'ನಿಮ್ಮ ಗುಪ್ತಪದವನ್ನು ನಮೂದಿಸಿ...',
      'ml': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക...',
      'ta': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்...',
      'te': 'మీ పాస్వర్డ్ ని నమోదుచేయండి...',
    },
    'b7tf9obg': {
      'en': 'Confirm Password',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'kn': 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
      'ml': 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      'ta': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'te': 'పాస్‌వర్డ్‌ని నిర్ధారించండి',
    },
    'xjodorrb': {
      'en': 'Enter your password...',
      'hi': 'अपना पासवर्ड डालें...',
      'kn': 'ನಿಮ್ಮ ಗುಪ್ತಪದವನ್ನು ನಮೂದಿಸಿ...',
      'ml': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക...',
      'ta': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்...',
      'te': 'మీ పాస్వర్డ్ ని నమోదుచేయండి...',
    },
    'gi9uuxaf': {
      'en': 'Create Account',
      'hi': 'खाता बनाएं',
      'kn': 'ಖಾತೆ ತೆರೆ',
      'ml': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'ta': 'உங்கள் கணக்கை துவங்குங்கள்',
      'te': 'ఖాతాను సృష్టించండి',
    },
    'aw5cnc76': {
      'en': 'Continue as Guest',
      'hi': 'अतिथि के रूप में जारी रखें',
      'kn': 'ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ',
      'ml': 'അതിഥിയായി തുടരുക',
      'ta': 'விருந்தினராக தொடரவும்',
      'te': 'అతిథిగా కొనసాగండి',
    },
    'sex0cy22': {
      'en': 'Home',
      'hi': 'घर',
      'kn': 'ಮುಖಪುಟ',
      'ml': 'വീട്',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // Miscellaneous
  {
    'hy5oorrw': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'lc2k8k7h': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'yc3owsxr': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'td8j7gjg': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '8avbi70n': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'hjprtz1r': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2j9mrifu': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'qzyoefrx': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '80a9ejmu': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'awxeoc4n': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'dz2izytu': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'wclfkgs7': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'spyzw2yi': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'dkdjstum': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '7wsb0twg': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mvnsfq3o': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'd5phwcm8': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '6b6eufx4': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'wysafec7': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'uoamr7rc': {
      'en': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
].reduce((a, b) => a..addAll(b));
